name: notes_todo
description: "A simple notes todo app for daily use."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Local storage & paths
  path_provider: ^2.1.5
  sqflite: ^2.4.2

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # Ads
  google_mobile_ads: ^6.0.0

  # Alarm & audio
  alarm: ^5.1.5
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/noteapp.png
    - assets/alarm.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/noteapp.png"
